---
title: "STS proposal comparison"
output:
  html_document:
    toc: true
    theme: cerulean
---

`r paste(system2('bin/sts-online', '--version', stdout=TRUE), collapse='')`.

Pipeline version `r system2('git', c('describe', '--always', '--dirty'), stdout=TRUE)`.

```{r}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
theme_set(theme_bw(16) + theme(axis.text.x = element_text(angle = 30, hjust = 1),
                               strip.background = element_blank()))

ess <- read.csv('output/ess_calls.csv', as.is=TRUE)
# R 3.1.0 "change"/bug
ess <- transform(ess,
                 last_ess = as.numeric(last_ess),
                 proposal = proposal_method_name,
                 n_taxa = paste(n_taxa, 'taxa'),
                 particle_factor = factor(particle_factor))
```

## Partials updates

Number of likelihood calls required by various proposal methods:

```{r, fig.width = 12}
p <- ggplot(ess, aes(x = proposal, y = likelihood_calls, fill = particle_factor)) +
  geom_boxplot() +
  facet_grid(n_taxa ~ trim_count) +
  scale_y_log10()
print(p)
```

## ... and effective sample size

```{r, fig.width = 12}
p <- ggplot(ess, aes(x = proposal, y = last_ess, fill = particle_factor)) +
  geom_boxplot() +
  facet_grid(n_taxa ~ trim_count)
print(p)
```

## Comparing the two

```{r, fig.width = 12}
p <- ggplot(ess, aes(x = proposal, y = likelihood_calls / last_ess, fill = particle_factor)) +
  geom_boxplot() +
  facet_grid(n_taxa ~ trim_count, scales = 'free_y') +
  scale_y_log10() +
  xlab('Proposal method') +
  ylab('# of partials updates per unit ESS')
print(p)
```

## Split probabilities

```{r, fig.width = 14}
df <- read.csv('output/pp_comparison.csv', as.is = TRUE)
df[, c('pp1', 'pp2')] <- sapply(df[, c('pp1', 'pp2')], as.numeric)
# Single leaf trimming
df <- transform(subset(df, !grepl('-', trim_taxon) & particle_factor == 1),
                proposal = proposal_method_name)

p <- ggplot(df, aes(x = pp1, y = pp2, color = type)) +
  geom_point() +
  facet_grid(n_taxa ~ proposal, scales = 'free_y') +
  coord_equal() +
  theme(legend.position = 'bottom')
print(p)

# Coefficient of determination
calc_rsq <- function(pp1, pp2) summary(lm(pp2 ~ pp1 + 0))$r.squared

rsq <- group_by(df, type, proposal, n_taxa) %>%
  summarize(rsq = calc_rsq(pp1, pp2),
            mse = mean((pp1 - pp2)^2)) %>%
  gather(variable, value, rsq:mse) %>%
  unite(var, variable, type) %>%
  spread(var, value) %>%
  select(-`mse_mrbayes-mrbayes`) %>%
  arrange(-`rsq_mrbayes-sts`)
```

#### Coefficient of determination
```{r, results = 'asis'}
knitr::kable(rsq)
```

## ASDSF

[Average Standard Deviation of Split Frequencies (ASDSF)](http://www.bali-phy.org/README.html#idp54307728)

```{r, fig.width = 10, fig.height = 10}
library(stringr)
asdsf <- read.csv('output/asdsf.csv', as.is=TRUE)

asdsf <- transform(asdsf, proposal = proposal_method_name,
                   n_trimmed = paste('trim', trim_count),
                   n_taxa = paste(n_taxa, 'taxa'))

p <- ggplot(asdsf, aes(x = proposal, y = asdsf, fill=type)) +
  geom_boxplot() +
  geom_hline(yintercept = 0.01, linetype = 'dashed') +
  facet_grid(n_trimmed ~ n_taxa) +
  theme(legend.position = 'bottom')
print(p)
```
